name: i18n
on: 
  push:
    branches-ignore:    
      - acceptance
      - main

permissions:
  contents: write

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: knitkode/koine/actions/i18n@main
