name: i18n
on: 
  push:
    branches-ignore:    
      - acceptance
      - main

jobs:
  i18n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: knitkode/koine/actions/i18n@main
